=== Footly/codearchitect/resources/codearchitect.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://json-schema.org/draft-07/schema#",
    "title": "Core schema meta-schema",
    "definitions": {
        "schemaArray": {
            "type": "array",
            "minItems": 1,
            "items": {
                "$ref": "#"
            }
        },
        "nonNegativeInteger": {
            "type": "integer",
            "minimum": 0
        },
        "nonNegativeIntegerDefault0": {
            "allOf": [
                {
                    "$ref": "#/definitions/nonNegativeInteger"
                },
                {
                    "default": 0
                }
            ]
        },
        "simpleTypes": {
            "enum": [
                "array",
                "boolean",
                "integer",
                "null",
                "number",
                "object",
                "string"
            ]
        },
        "stringArray": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "uniqueItems": true,
            "default": []
        }
    },
    "type": [
        "object",
        "boolean"
    ],
    "properties": {
        "$id": {
            "type": "string",
            "format": "uri-reference"
        },
        "$schema": {
            "type": "string",
            "format": "uri"
        },
        "$ref": {
            "type": "string",
            "format": "uri-reference"
        },
        "title": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "items": {
            "anyOf": [
                {
                    "$ref": "#"
                },
                {
                    "$ref": "#/definitions/schemaArray"
                }
            ],
            "default": true
        },
        "required": {
            "$ref": "#/definitions/stringArray"
        },
        "properties": {
            "type": "object",
            "additionalProperties": {
                "$ref": "#"
            },
            "default": {}
        },
        "const": true,
        "enum": {
            "type": "array",
            "items": true
        },
        "type": {
            "anyOf": [
                {
                    "$ref": "#/definitions/simpleTypes"
                },
                {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/simpleTypes"
                    }
                }
            ]
        },
        "modelType": {
            "type": "string",
            "enum": [
              "root",
              "parent-object",
              "folder",
              "input-string",
              "checkbox",
              "dropdown-select",
              "dropdown-select-tag",
              "sub-object",
              "text-area",
              "pool-dropdown-select-tag"

          ]
        },
        "hidden": {
            "type":"boolean"
        },
        "vscodeIcon": {
            "type": "string"
        },
        "$link": {
            "type": "object",
            "properties": {
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "scope": {
                    "type": "string",
                    "enum": [
                        "global",
                        "local",
                        "parent",
                        "none"
                    ]
                }
            }
        },
        "default": true
    }
}

=== Footly/codearchitect/workspace/schemas/macro.model.json
{
    "$schema": "file:///C:/Users/narcis.oriol/Documents/codearchitect/codearchitect_3/resources/codearchitect.schema.json",
    "type": "object",
    "title": "Macro",
    "vscodeIcon": "symbol-number",
    "modelType": "parent-object",
    "properties": {
      "$id": {
        "type": "string",
        "hidden": true
      },
      "$label": {
        "type": "string",
        "hidden": true
      },
      "visibility": {
        "hidden": true,
        "$ref": "./visibility.model.json",
        "const": "public"
      },
      "value": {
        "type": "string",
        "hidden": true,
        "modelType": "input-string",
        "const": [
            "macro",
            "enummember"
        ]
      }
    },
    "$link": {
      "tags": ["*", "macro"]
    }
  }

=== Footly/codearchitect/workspace/schemas/typedefs.model.json
{
  "$schema": "file:///C:/Users/narcis.oriol/Documents/codearchitect/codearchitect_3/resources/codearchitect.schema.json",
  "type": "object",
  "title": "Typedef",
  "vscodeIcon": "references",
  "modelType": "parent-object",
  "properties": {
    "$id": {
      "type": "string",
      "hidden": true
    },
    "$label": {
      "type": "string",
      "hidden": true
    },
    "visibility": {
      "hidden": true,
      "modelType": "dropdown-select",
      "$ref": "./visibility.model.json"
    },
    "datatype": {
      "hidden": true,
      "modelType": "dropdown-select-tag",
      "type": "string",
      "const": ["types"]
    },
    "documentation": {
      "hidden": true,
      "modelType": "input-string",
      "type": "string"
    }
  },
  "$link": {
    "tags": ["*", "types"]
  }
}

=== Footly/codearchitect/workspace/schemas/enummember.model.json
{
  "$schema": "file:///C:/Users/narcis.oriol/Documents/codearchitect/codearchitect_3/resources/codearchitect.schema.json",
  "type": "object",
  "title": "EnumMember",
  "modelType": "parent-object",
  "vscodeIcon": "symbol-field",
  "properties": {
    "$id": {
      "type": "string",
      "hidden": true
    },
    "$label": {
      "type": "string",
      "hidden": true
    },
    "visibility": {
      "hidden": true,
      "$ref": "./visibility.model.json",
      "const": "public"
    },
    "dependencies": {
      "hidden": true,
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "scope": {
      "hidden": true,
      "type": "string"
    },
    "value": {
      "hidden": true,
      "modelType": "input-string",
      "type":"string"
    }
  },
  "$link": {
    "scope": "parent",
    "tags": ["*", "enummeber"]
  }
}
